### PR TITLE
Create new tutorial for groups and communicators

### PR DESCRIPTION
**Pull request by wesbland**
This creates a new tutorial covering groups and communicators, including
how they are created, manipulated, and freed.

### CODE REVIEW

**Comment by wesleykendall** [comment]
@wesbland this is awesome! Some initial thoughts after skimming over this:
- Groups / communicators seems fairly advanced for a beginner tutorial. Do you think it would be wise to simply make the beginner tutorial a list of all tutorials in order of ascending difficulty? That's something I can take care of if you are onboard with it
- Does groups / communicators warrant a section of it's own? If there are a couple more ideas you can think of that might eventually compose that section, I'm good with keeping it in its own section

I'll compile it locally later and add some more comments. Also, I'm down to add you as a collaborator with full write access if you'd like. I may eventually move this repo to a different owner (mpitutorial perhaps) if the community wants to continue adding really great tutorials. You are the second different author in the past month to contribute to it, and I'm really excited about where it will go!

One more thing to make you aware of - I get affiliate commission off of Amazon links on the recommended books section. It's a very tiny amount every month that used to cover hosting before I put it on Github. You are always welcome to put affiliate links to great MPI books in your tutorials if those are books you would recommend.

**Comment by wesbland** [comment]
You're probably right that this could go under a more advanced section. I can move it over later today.

You're probably also right about having another section. I only put it in a new section because it didn't really make sense in any of the existing sections. I welcome any other suggestions on where to put it.

It's up to you whether you want to give me write access or not. I'm fine either way. I plan on also writing a tutorial on non-blocking communication since that's something where I see a lot of people have issues. That will probably take another few weeks to find the time to do it. This tends to be something I do when I'm on travel and don't have baby duty.

**Comment by wesleykendall** [comment]
@dtsdwarak do you have any comments on this? I should be able to get around to it tomorrow

**Comment by dtsdwarak** [comment]
@wesleykendall : Looks fine to me!

**Comment by wesleykendall** [comment]
@wesbland looks good to me. Come to think of it, how about I go ahead and just put everything under the "Tutorial" part and no longer separate beginner and advanced. If we get enough content, we can split it later. Does that work?

**Comment by wesbland** [comment]
Sounds good to me.

**Comment by wesbland** [comment]
Makes sense to me.

**Pull request merged**
