### PR TITLE
add zh version for mpi-broadcast-and-collective-communication

### PR DESCRIPTION
**Pull request by joe-dddd**

### CODE REVIEW

**Comment by wesleykendall** [comment]
@wesbland have any thoughts? I was checking out the last translations and it looks like we add a "translations" tag to the pages that are translated. Wasn't sure how to proceed

**Comment by wesbland** [comment]
You're right @wesleykendall. I fixed that part of this PR, but when I built the website locally, I got a weird error message and the zh version of the new tutorial didn't load with proper formatting:

```
$ bundle exec jekyll serve
Configuration file: ..snip../mpitutorial/_config.yml
            Source: ..snip../mpitutorial
       Destination: ..snip../mpitutorial/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
Error reading file ..snip../mpitutorial/tutorials/mpi-broadcast-and-collective-communication/zh_cn.md: (<unknown>): control characters are not allowed at line 1 column 1
                    done in 1.314 seconds.
 Auto-regeneration: enabled for '..snip../mpitutorial'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

screen shot 2018-07-23 at 9 14 37 am


@cckn1ght - Can you take a look at that and see what the problem might be? It wasn't immediately obvious to me, though I didn't spend a lot of time digging into it.

**Comment by joe-dddd** [comment]
Ok fixed. It turns out Jekyll doesn't like the Unicode （ in the Frontmatter title part. I changed it to the ascii one. I guess it's because (: is the right way to smile rather than （:。

**Comment by wesbland** [comment]
Yep. That took care of it. :shipit:

**Pull request merged**
