### PR TITLE
add Chinese translation for mpi-introduction

### PR DESCRIPTION
**Pull request by joe-dddd**
Hello Kendall, I have learned so much from your tutorial! I'd like to add Chinese translation to this tutorial to help more people accessing this incredible resource!

### CODE REVIEW

**Comment by wesbland** [comment]
If we're going to add translations, we probably need to link to it on the main tutorials page somehow. Maybe by adding `[CN]` after the name of the tutorial?

**Comment by joe-dddd** [comment]
How about trying the style used by this article? https://medium.com/@ageitgey/machine-learning-is-fun-80ea3ec3c471   I have made some changes according to this.

**Comment by wesbland** [comment]
I prefer to put the list of translations in the header so it doesn't clutter up the article itself (though that's a great article you've linked to). I've added a couple of patches to your branch that I think accomplish that.

What do you think?

Screenshot of what it looks like:

screen shot 2018-05-16 at 9 41 46 am

**Comment by Z-Y00** [comment]
good job ! Looking forward for your translation !  I will try to collation the translation if I can

**Comment by joe-dddd** [comment]
@wesleykendall Your idea makes perfect sense to me! Let's do it that way.

**Comment by wesleykendall** [comment]
@wesbland thanks for the suggestions and for taking care of this!

**Pull request merged**
